/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import Link from 'next/link';
import React,{ useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'


export async function getStaticProps(){
  const resp = await fetch(
    'https://jherr-pokemon.s3.us-west-1.amazonaws.com/index.json'
    );
    return {
      props:{
        pokemons: await resp.json(),
      },
    }
}

export default function Home({pokemons}) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Pokemon List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.grid}>
        {pokemons.map((pokemon)=>{
          return (
            <div className={styles.card} key={pokemon.id}>
              <Link href={`/pokemon/${pokemon.id}`}>
                <a>
                  <img
                    src={`https://jherr-pokemon.s3.us-west-1.amazonaws.com/${pokemon.image}`}
                    alt={pokemon.name}
                  />
                  <h3>{pokemon.name}</h3>
                </a>
              </Link>
            </div>
          );
        })}
      </div>
    </div>
  )
}
